const PWA_VERSION_KEY = 'bepi-pwa-last-version';
const PWA_RELOAD_KEY = 'bepi-pwa-reloaded-once';
const CHECK_INTERVAL_MS = 20 * 60 * 1000;
const FLOW_BUILD = 'flow-v38';
let swRegistration = null;
let updateTimer = null;
function showUpdateToast(text){const toast=document.getElementById('toast');if(!toast)return;toast.textContent=text;toast.classList.add('show');clearTimeout(showUpdateToast.t);showUpdateToast.t=setTimeout(()=>toast.classList.remove('show'),4200)}
function injectCompactTestCss(){if(document.getElementById('compact-test-overrides'))return;const s=document.createElement('style');s.id='compact-test-overrides';s.textContent='.test-product-eval{padding:7px!important;border-radius:12px!important;gap:5px!important}.test-product-eval h4{font-size:13px!important;margin:0 0 4px!important;line-height:1.2!important}.test-checks{display:flex!important;flex-wrap:wrap!important;gap:5px!important}.test-checks label{padding:4px 6px!important;border-radius:999px!important;font-size:12px!important;background:#f4fbf9!important}.test-product-eval .test-field{gap:3px!important}.test-product-eval .test-field span{font-size:11px!important}.test-product-eval select{min-height:32px!important;padding:5px 8px!important}.test-product-eval textarea{min-height:38px!important}.test-product-eval input{min-height:32px!important}.test-products{gap:6px!important}.test-customer-form{gap:8px!important}.test-customer-form h3{margin:4px 0!important;font-size:15px!important}';document.head.appendChild(s)}
function askWorkerToActivate(worker){if(!worker)return;try{worker.postMessage({type:'SKIP_WAITING'})}catch(error){console.warn('Cannot activate new service worker',error)}}
function watchInstallingWorker(worker){if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){showUpdateToast('New app version is updating...');askWorkerToActivate(worker)}})}
async function checkForUpdate(){if(!swRegistration)return;try{await swRegistration.update()}catch(error){console.warn('PWA update check failed',error)}}
async function checkVersionFile(){try{const res=await fetch(`./version.json?t=${Date.now()}`,{cache:'no-store'});if(!res.ok)return;const data=await res.json();const version=String(data.version||'').trim()||FLOW_BUILD;const old=localStorage.getItem(PWA_VERSION_KEY);localStorage.setItem(PWA_VERSION_KEY,version);if(old&&old!==version){showUpdateToast('New app version is loading...');setTimeout(()=>location.reload(),900)}}catch(error){console.warn('Version check failed',error)}}
async function startPwaUpdate(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(sessionStorage.getItem(PWA_RELOAD_KEY)==='1')return;sessionStorage.setItem(PWA_RELOAD_KEY,'1');showUpdateToast('App updated. Reloading...');setTimeout(()=>location.reload(),700)});try{swRegistration=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});watchInstallingWorker(swRegistration.installing);if(swRegistration.waiting)askWorkerToActivate(swRegistration.waiting);swRegistration.addEventListener('updatefound',()=>watchInstallingWorker(swRegistration.installing));await checkForUpdate();await checkVersionFile();clearInterval(updateTimer);updateTimer=setInterval(()=>{checkForUpdate();checkVersionFile()},CHECK_INTERVAL_MS);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){checkForUpdate();checkVersionFile()}})}catch(error){console.warn('Service worker registration failed',error)}}
window.addEventListener('load',startPwaUpdate);
window.addEventListener('load',()=>{document.querySelector('link[rel="manifest"]')?.remove();injectCompactTestCss();import(`./test-module.js?v=${FLOW_BUILD}`).catch((error)=>console.warn('Cannot load test module',error))});
