const PWA_VERSION_KEY = 'bepi-pwa-last-version';
const PWA_RELOAD_KEY = 'bepi-pwa-reloaded-once';
const CHECK_INTERVAL_MS = 20 * 60 * 1000;
const FLOW_BUILD = 'flow-v40';
let swRegistration = null;
let updateTimer = null;
function showUpdateToast(text){const toast=document.getElementById('toast');if(!toast)return;toast.textContent=text;toast.classList.add('show');clearTimeout(showUpdateToast.t);showUpdateToast.t=setTimeout(()=>toast.classList.remove('show'),4200)}
function storageSettings(){try{return JSON.parse(localStorage.getItem('bepi-field-report-v5')||'{"settings":{}}')}catch{return{settings:{}}}}
function normalizeSupabaseUrl(value=''){return String(value||'').trim().replace(/\/rest\/v1\/?$/i,'').replace(/\/+$/,'')}
function injectAdminCss(){if(document.getElementById('admin-db-inline-css'))return;const s=document.createElement('style');s.id='admin-db-inline-css';s.textContent='.admin-db-inline{display:grid;gap:10px;margin:-8px 0 14px;padding:14px;border:1px solid #cfe8e3;border-radius:18px;background:#fff}.admin-db-inline label{display:grid;gap:6px;font-weight:800;font-size:12px}.admin-db-inline input{min-height:42px;border:1px solid #cfe1dc;border-radius:12px;padding:8px 10px;box-sizing:border-box;width:100%}.admin-db-inline-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.admin-db-inline-actions button{min-height:42px;border-radius:12px!important;font-weight:900!important}.admin-db-inline small{color:#60736f;line-height:1.35}.db-pill.off span{background:#ff4438!important}@media(max-width:420px){.admin-db-inline-actions{grid-template-columns:1fr}}';document.head.appendChild(s)}
function ensureInlineDbForm(){injectAdminCss();if(document.getElementById('adminDbInline'))return;const card=document.querySelector('.admin-card.db');if(!card)return;card.insertAdjacentHTML('afterend','<section class="admin-db-inline" id="adminDbInline"><label>Supabase Project URL<input id="quickSupabaseUrl" type="url" placeholder="https://xxxxx.supabase.co"></label><label>Supabase publishable / anon key<input id="quickSupabaseAnonKey" type="password" placeholder="sb_publishable_..."></label><div class="admin-db-inline-actions"><button type="button" id="quickTestSupabaseBtn">Test DB</button><button class="primary" type="button" id="quickSaveSupabaseBtn">Lưu DB</button></div><small id="quickSupabaseStatus">Nhập URL/key rồi bấm Lưu DB. Không dùng service_role/sb_secret.</small></section>')}
function updateAdminUi(){ensureInlineDbForm();const data=storageSettings();const url=normalizeSupabaseUrl(data.settings?.supabaseUrl||'');const key=String(data.settings?.supabaseAnonKey||'').trim();const ready=/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(url)&&Boolean(key)&&!/sb_secret_|service_role/i.test(key);[['supabaseUrl',url],['quickSupabaseUrl',url]].forEach(([id,val])=>{const n=document.getElementById(id);if(n&&!n.value)n.value=val});[['supabaseAnonKey',key],['quickSupabaseAnonKey',key]].forEach(([id,val])=>{const n=document.getElementById(id);if(n&&!n.value)n.value=val});const preview=document.getElementById('supabasePreviewStatus');const state=document.getElementById('adminDbState');const pill=document.getElementById('dbStatusPill');if(preview)preview.innerHTML=ready?`URL Project: ${url}<br>Anon Key: đã lưu`:'URL Project: -<br>Anon Key: -';if(state)state.textContent=ready?'Đã nối ›':'Chưa nối ›';if(pill){pill.classList.toggle('off',!ready);const b=pill.querySelector('b');if(b)b.textContent=ready?'Đã nối Supabase':'Chưa nối Supabase'}return{ready,url,key}}
function readDbInputs(kind='dialog'){const quick=kind==='quick';const url=normalizeSupabaseUrl(document.getElementById(quick?'quickSupabaseUrl':'supabaseUrl')?.value||'');const key=String(document.getElementById(quick?'quickSupabaseAnonKey':'supabaseAnonKey')?.value||'').trim();const status=document.getElementById(quick?'quickSupabaseStatus':'supabaseStatus');return{url,key,status}}
function saveDb(kind='dialog'){const{url,key,status}=readDbInputs(kind);if(/sb_secret_|service_role/i.test(key)){if(status)status.textContent='Sai key: không dùng service_role/sb_secret trong PWA.';showUpdateToast('Không lưu secret key.');return false}if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(url)||!key){if(status)status.textContent='Thiếu URL/key Supabase hợp lệ.';showUpdateToast('Thiếu URL/key.');return false}const data=storageSettings();data.settings={...(data.settings||{}),supabaseUrl:url,supabaseAnonKey:key};localStorage.setItem('bepi-field-report-v5',JSON.stringify(data));updateAdminUi();if(status)status.textContent='Đã lưu Supabase trên máy này.';showUpdateToast('Đã lưu DB.');return true}
async function testDb(kind='dialog'){const saved=saveDb(kind);const{url,key,status}=readDbInputs(kind);if(!saved)return;try{const res=await fetch(`${url}/rest/v1/products?select=id,name&limit=1`,{headers:{apikey:key,Authorization:`Bearer ${key}`}});if(!res.ok)throw new Error(`Supabase HTTP ${res.status}`);if(status)status.textContent='DB sẵn sàng. Đọc được bảng products.';showUpdateToast('DB OK.')}catch(err){if(status)status.textContent=err.message||'Không test được DB.';showUpdateToast('Test DB lỗi.')}}
function bindAdminFallback(){ensureInlineDbForm();document.addEventListener('click',async(e)=>{if(e.target.closest('#quickSaveSupabaseBtn')){e.preventDefault();e.stopPropagation();saveDb('quick');return}if(e.target.closest('#quickTestSupabaseBtn')){e.preventDefault();e.stopPropagation();await testDb('quick');return}if(e.target.closest('#saveSupabaseBtn')){e.preventDefault();e.stopPropagation();saveDb('dialog');return}if(e.target.closest('#testSupabaseBtn')){e.preventDefault();e.stopPropagation();await testDb('dialog');return}const open=e.target.closest('[data-open-dialog]');if(open){const d=document.getElementById(open.dataset.openDialog);if(d?.showModal)d.showModal();else d?.setAttribute('open','');setTimeout(updateAdminUi,0);return}const close=e.target.closest('[data-close-dialog]');if(close){const d=close.closest('dialog');if(d?.close)d.close();else d?.removeAttribute('open')}});updateAdminUi()}
function injectCompactTestCss(){if(document.getElementById('compact-test-overrides'))return;const s=document.createElement('style');s.id='compact-test-overrides';s.textContent='.test-product-eval{padding:7px!important;border-radius:12px!important;gap:5px!important}.test-product-eval h4{font-size:13px!important;margin:0 0 4px!important;line-height:1.2!important}.test-checks{display:flex!important;flex-wrap:wrap!important;gap:5px!important}.test-checks label{padding:4px 6px!important;border-radius:999px!important;font-size:12px!important;background:#f4fbf9!important}.test-product-eval .test-field{gap:3px!important}.test-product-eval .test-field span{font-size:11px!important}.test-product-eval select{min-height:32px!important;padding:5px 8px!important}.test-product-eval textarea{min-height:38px!important}.test-product-eval input{min-height:32px!important}.test-products{gap:6px!important}.test-customer-form{gap:8px!important}.test-customer-form h3{margin:4px 0!important;font-size:15px!important}';document.head.appendChild(s)}
function askWorkerToActivate(worker){if(!worker)return;try{worker.postMessage({type:'SKIP_WAITING'})}catch(error){console.warn('Cannot activate new service worker',error)}}
function watchInstallingWorker(worker){if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){showUpdateToast('New app version is updating...');askWorkerToActivate(worker)}})}
async function checkForUpdate(){if(!swRegistration)return;try{await swRegistration.update()}catch(error){console.warn('PWA update check failed',error)}}
async function checkVersionFile(){try{const res=await fetch(`./version.json?t=${Date.now()}`,{cache:'no-store'});if(!res.ok)return;const data=await res.json();const version=String(data.version||'').trim()||FLOW_BUILD;const old=localStorage.getItem(PWA_VERSION_KEY);localStorage.setItem(PWA_VERSION_KEY,version);if(old&&old!==version){showUpdateToast('New app version is loading...');setTimeout(()=>location.reload(),900)}}catch(error){console.warn('Version check failed',error)}}
async function startPwaUpdate(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(sessionStorage.getItem(PWA_RELOAD_KEY)==='1')return;sessionStorage.setItem(PWA_RELOAD_KEY,'1');showUpdateToast('App updated. Reloading...');setTimeout(()=>location.reload(),700)});try{swRegistration=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});watchInstallingWorker(swRegistration.installing);if(swRegistration.waiting)askWorkerToActivate(swRegistration.waiting);swRegistration.addEventListener('updatefound',()=>watchInstallingWorker(swRegistration.installing));await checkForUpdate();await checkVersionFile();clearInterval(updateTimer);updateTimer=setInterval(()=>{checkForUpdate();checkVersionFile()},CHECK_INTERVAL_MS);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){checkForUpdate();checkVersionFile()}})}catch(error){console.warn('Service worker registration failed',error)}}
window.addEventListener('load',startPwaUpdate);
window.addEventListener('load',()=>{document.querySelector('link[rel="manifest"]')?.remove();bindAdminFallback();injectCompactTestCss();import(`./test-module.js?v=${FLOW_BUILD}`).catch((error)=>console.warn('Cannot load test module',error))});
