const PWA_VERSION_KEY = 'bepi-pwa-last-version';
const PWA_RELOAD_KEY = 'bepi-pwa-reloaded-once';
const CHECK_INTERVAL_MS = 20 * 60 * 1000;
const FLOW_BUILD = 'flow-v39';
let swRegistration = null;
let updateTimer = null;
function showUpdateToast(text){const toast=document.getElementById('toast');if(!toast)return;toast.textContent=text;toast.classList.add('show');clearTimeout(showUpdateToast.t);showUpdateToast.t=setTimeout(()=>toast.classList.remove('show'),4200)}
function storageSettings(){try{return JSON.parse(localStorage.getItem('bepi-field-report-v5')||'{"settings":{}}')}catch{return{settings:{}}}}
function normalizeSupabaseUrl(value=''){return String(value||'').trim().replace(/\/rest\/v1\/?$/i,'').replace(/\/+$/,'')}
function updateAdminUi(){const data=storageSettings();const url=normalizeSupabaseUrl(data.settings?.supabaseUrl||'');const key=String(data.settings?.supabaseAnonKey||'').trim();const ready=/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(url)&&Boolean(key)&&!/sb_secret_|service_role/i.test(key);const urlInput=document.getElementById('supabaseUrl');const keyInput=document.getElementById('supabaseAnonKey');const preview=document.getElementById('supabasePreviewStatus');const state=document.getElementById('adminDbState');const pill=document.getElementById('dbStatusPill');if(urlInput&&!urlInput.value)urlInput.value=url;if(keyInput&&!keyInput.value)keyInput.value=key;if(preview)preview.innerHTML=ready?`URL Project: ${url}<br>Anon Key: đã lưu`:'URL Project: -<br>Anon Key: -';if(state)state.textContent=ready?'Đã nối ›':'Chưa nối ›';if(pill){pill.classList.toggle('off',!ready);const b=pill.querySelector('b');if(b)b.textContent=ready?'Đã nối Supabase':'Chưa nối Supabase'}return{ready,url,key}}
function bindAdminFallback(){document.addEventListener('click',async(e)=>{const open=e.target.closest('[data-open-dialog]');if(open){const d=document.getElementById(open.dataset.openDialog);if(d?.showModal)d.showModal();else d?.setAttribute('open','');setTimeout(updateAdminUi,0);return}const close=e.target.closest('[data-close-dialog]');if(close){const d=close.closest('dialog');if(d?.close)d.close();else d?.removeAttribute('open');return}if(e.target.closest('#saveSupabaseBtn')){const url=normalizeSupabaseUrl(document.getElementById('supabaseUrl')?.value||'');const key=String(document.getElementById('supabaseAnonKey')?.value||'').trim();const status=document.getElementById('supabaseStatus');if(/sb_secret_|service_role/i.test(key)){if(status)status.textContent='Sai key: không dùng service_role/sb_secret trong PWA.';showUpdateToast('Không lưu secret key.');return}const data=storageSettings();data.settings={...(data.settings||{}),supabaseUrl:url,supabaseAnonKey:key};localStorage.setItem('bepi-field-report-v5',JSON.stringify(data));updateAdminUi();if(status)status.textContent='Đã lưu Supabase trên máy này.';showUpdateToast('Đã lưu DB.');return}if(e.target.closest('#testSupabaseBtn')){const status=document.getElementById('supabaseStatus');const cfg=updateAdminUi();if(!cfg.ready){if(status)status.textContent='Thiếu URL/key Supabase hợp lệ.';showUpdateToast('DB chưa sẵn sàng.');return}try{const res=await fetch(`${cfg.url}/rest/v1/products?select=id,name&limit=1`,{headers:{apikey:cfg.key,Authorization:`Bearer ${cfg.key}`}});if(!res.ok)throw new Error(`Supabase HTTP ${res.status}`);if(status)status.textContent='DB sẵn sàng. Đọc được products.';showUpdateToast('DB OK.')}catch(err){if(status)status.textContent=err.message||'Không test được DB.';showUpdateToast('Test DB lỗi.')}}});updateAdminUi()}
function injectCompactTestCss(){if(document.getElementById('compact-test-overrides'))return;const s=document.createElement('style');s.id='compact-test-overrides';s.textContent='.test-product-eval{padding:7px!important;border-radius:12px!important;gap:5px!important}.test-product-eval h4{font-size:13px!important;margin:0 0 4px!important;line-height:1.2!important}.test-checks{display:flex!important;flex-wrap:wrap!important;gap:5px!important}.test-checks label{padding:4px 6px!important;border-radius:999px!important;font-size:12px!important;background:#f4fbf9!important}.test-product-eval .test-field{gap:3px!important}.test-product-eval .test-field span{font-size:11px!important}.test-product-eval select{min-height:32px!important;padding:5px 8px!important}.test-product-eval textarea{min-height:38px!important}.test-product-eval input{min-height:32px!important}.test-products{gap:6px!important}.test-customer-form{gap:8px!important}.test-customer-form h3{margin:4px 0!important;font-size:15px!important}';document.head.appendChild(s)}
function askWorkerToActivate(worker){if(!worker)return;try{worker.postMessage({type:'SKIP_WAITING'})}catch(error){console.warn('Cannot activate new service worker',error)}}
function watchInstallingWorker(worker){if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){showUpdateToast('New app version is updating...');askWorkerToActivate(worker)}})}
async function checkForUpdate(){if(!swRegistration)return;try{await swRegistration.update()}catch(error){console.warn('PWA update check failed',error)}}
async function checkVersionFile(){try{const res=await fetch(`./version.json?t=${Date.now()}`,{cache:'no-store'});if(!res.ok)return;const data=await res.json();const version=String(data.version||'').trim()||FLOW_BUILD;const old=localStorage.getItem(PWA_VERSION_KEY);localStorage.setItem(PWA_VERSION_KEY,version);if(old&&old!==version){showUpdateToast('New app version is loading...');setTimeout(()=>location.reload(),900)}}catch(error){console.warn('Version check failed',error)}}
async function startPwaUpdate(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(sessionStorage.getItem(PWA_RELOAD_KEY)==='1')return;sessionStorage.setItem(PWA_RELOAD_KEY,'1');showUpdateToast('App updated. Reloading...');setTimeout(()=>location.reload(),700)});try{swRegistration=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});watchInstallingWorker(swRegistration.installing);if(swRegistration.waiting)askWorkerToActivate(swRegistration.waiting);swRegistration.addEventListener('updatefound',()=>watchInstallingWorker(swRegistration.installing));await checkForUpdate();await checkVersionFile();clearInterval(updateTimer);updateTimer=setInterval(()=>{checkForUpdate();checkVersionFile()},CHECK_INTERVAL_MS);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){checkForUpdate();checkVersionFile()}})}catch(error){console.warn('Service worker registration failed',error)}}
window.addEventListener('load',startPwaUpdate);
window.addEventListener('load',()=>{document.querySelector('link[rel="manifest"]')?.remove();bindAdminFallback();injectCompactTestCss();import(`./test-module.js?v=${FLOW_BUILD}`).catch((error)=>console.warn('Cannot load test module',error))});
