const FORM_KEY = 'bepi-local-market-forms-v1';
const ROW_KEY = 'bepi-local-market-rows-v1';
let activeFormId = '';
let modal, formEl, listEl;

const $ = (s, r = document) => r.querySelector(s);
const $$ = (s, r = document) => Array.from(r.querySelectorAll(s));
const esc = (v = '') => String(v ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
const read = k => { try { const v = JSON.parse(localStorage.getItem(k) || '[]'); return Array.isArray(v) ? v : []; } catch { return []; } };
const write = (k, v) => localStorage.setItem(k, JSON.stringify(Array.isArray(v) ? v : []));
const uid = (p = 'id') => `${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
const today = () => new Date().toISOString().slice(0, 10);
const shortDate = d => { const p = String(d || '').split('-'); return p.length === 3 ? `${p[2]}-${p[1]}` : today().slice(5).split('-').reverse().join('-'); };
const toast = msg => { const t = $('#toast'); if (!t) return; t.textContent = msg; t.classList.add('show'); clearTimeout(toast.t); toast.t = setTimeout(() => t.classList.remove('show'), 2300); };

function injectCss() {
  if ($('#marketFlowCss')) return;
  const s = document.createElement('style');
  s.id = 'marketFlowCss';
  s.textContent = `.market-modal[hidden]{display:none!important}.market-modal{position:fixed;inset:0;z-index:999;display:grid;place-items:center;background:rgba(0,0,0,.42);padding:12px}.market-sheet{width:min(440px,100%);max-height:92vh;overflow:auto;border-radius:20px;background:#f8fcfb}.market-head{padding:14px;background:#00897b;color:white;border-radius:20px 20px 0 0}.market-head-row{display:flex;justify-content:space-between;gap:10px}.market-head h2{margin:4px 0}.market-body,.market-form,.market-card,.market-customer-form{display:grid;gap:10px}.market-body{padding:12px 12px 82px}.market-card,.market-summary,.market-customer-form{padding:12px;border:1px solid #d8ebe6;border-radius:16px;background:white}.market-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.market-field{display:grid!important;gap:5px}.market-field span{font-size:12px;font-weight:800}.market-field input,.market-field select,.market-field textarea{width:100%;min-height:38px;border:1px solid #cfe1dc;border-radius:10px;padding:7px 9px;box-sizing:border-box}.market-footer{position:sticky;bottom:0;display:grid;grid-template-columns:1fr 1.2fr;gap:8px;padding:10px 12px;background:#f8fcfb;border-top:1px solid #d8ebe6}.market-footer button,.market-primary{min-height:42px;border-radius:12px!important;font-weight:900!important}.market-file,.market-row{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;cursor:pointer}.market-file h3,.market-row h3{margin:0;font-size:15px}.market-file small,.market-row small{color:#60736f}.market-pills{display:flex;flex-wrap:wrap;gap:5px;margin-top:6px}.market-pills span{padding:5px 8px;border-radius:999px;background:#eaf8f5;color:#00796b;font-size:12px;font-weight:900}.market-detail-top{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:10px}.market-observe{padding:9px;border:1px solid #d8ebe6;border-radius:13px;background:white}.ok-pop{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;background:rgba(0,0,0,.38);padding:18px}.ok-card{display:grid;gap:10px;width:min(340px,100%);background:white;border-radius:20px;padding:18px}@media(max-width:420px){.market-modal{align-items:end;padding:0}.market-sheet{width:100%;border-radius:20px 20px 0 0}.market-grid,.market-file,.market-row{grid-template-columns:1fr}.market-detail-top{align-items:stretch;flex-direction:column}}`;
  document.head.appendChild(s);
}

function ensureModal() {
  if ($('#marketFormPanel')) return;
  document.body.insertAdjacentHTML('beforeend', `<section class="market-modal" id="marketFormPanel" hidden><div class="market-sheet"><div class="market-head"><div class="market-head-row"><div><b>FORM BÁO CÁO TỔNG</b><h2>Tạo file báo cáo</h2><small>File tổng theo ngày/tuyến. Khách khảo sát nhập trong chi tiết.</small></div><button type="button" id="closeMarketFormBtn">×</button></div></div><form id="marketForm" class="market-form"><div class="market-body"><section class="market-card"><h3>Thông tin file</h3><div class="market-grid"><label class="market-field"><span>Ngày</span><input type="date" id="marketDate" required></label><label class="market-field"><span>Sales</span><input id="marketSales" value="A Tân"></label></div><label class="market-field"><span>Khu vực / tuyến</span><input id="marketRoute" required placeholder="VD: Bến Tre"></label><label class="market-field"><span>Tên file báo cáo</span><input id="marketTitle" placeholder="Để trống sẽ tự tạo"></label><label class="market-field"><span>Mục tiêu / ghi chú</span><textarea id="marketNote" placeholder="Mục tiêu khảo sát, đối thủ cần xem, nhu cầu..."></textarea></label></section></div><div class="market-footer"><button type="button" id="resetMarketBtn">Xóa</button><button type="submit" class="primary">Lưu file tổng</button></div></form></div></section>`);
  modal = $('#marketFormPanel');
  formEl = $('#marketForm');
}

function ensureList() {
  const panel = document.querySelector('[data-data-panel="reports"]');
  if (!panel) return;
  panel.innerHTML = '<div id="marketReportList"></div>';
  listEl = $('#marketReportList');
}
function resetForm() { formEl.reset(); $('#marketDate').value = today(); $('#marketSales').value = 'A Tân'; }
function openForm() { modal.hidden = false; document.body.style.overflow = 'hidden'; }
function closeForm() { modal.hidden = true; document.body.style.overflow = ''; }
function activateReports() { document.querySelectorAll('.app-page').forEach(p => p.classList.toggle('is-active', p.id === 'dataSection')); document.querySelectorAll('[data-page-link]').forEach(a => a.classList.toggle('is-active', a.dataset.pageLink === 'dataSection')); document.querySelectorAll('[data-data-view]').forEach(b => b.classList.toggle('is-active', b.dataset.dataView === 'reports')); document.querySelectorAll('[data-data-panel]').forEach(p => p.classList.toggle('is-active', p.dataset.dataPanel === 'reports')); }
function rowsOf(id) { return read(ROW_KEY).filter(r => r.form_id === id); }
function saveFile(e) { e.preventDefault(); const route = $('#marketRoute').value.trim(); const date = $('#marketDate').value || today(); if (!route) return toast('Thiếu khu vực / tuyến.'); const file = { id: uid('market-file'), route, report_date: date, sales: $('#marketSales').value.trim(), title: $('#marketTitle').value.trim() || `${route}-${shortDate(date)}`, note: $('#marketNote').value.trim(), created_at: new Date().toISOString(), sync_status: 'local' }; const rows = read(FORM_KEY); rows.unshift(file); write(FORM_KEY, rows); activeFormId = ''; resetForm(); closeForm(); activateReports(); renderReports(); toast('Đã lưu file báo cáo.'); }
function filesHtml() { const files = read(FORM_KEY).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))); if (!files.length) return '<h3>Báo cáo</h3><article class="record-card"><p>Chưa có file báo cáo. Tạo từ màn Tạo → Báo cáo thị trường.</p></article>'; return `<h3>Báo cáo</h3>${files.map(f => `<article class="record-card market-file" data-open-report="${esc(f.id)}"><div><h3>${esc(f.title)}</h3><small>${esc(f.report_date)} · ${esc(f.sales || '-')} · ${rowsOf(f.id).length} khách</small><div class="market-pills"><span>${esc(f.route || '-')}</span><span>Local</span></div></div><b>Mở ›</b></article>`).join('')}`; }
function customerForm(f) { return `<form id="marketCustomerForm" class="market-customer-form" data-form-id="${esc(f.id)}"><h3>Thêm khách khảo sát</h3><div class="market-grid"><label class="market-field"><span>Khách hàng</span><input id="marketCustomerName" required></label><label class="market-field"><span>SĐT</span><input id="marketCustomerPhone"></label></div><div class="market-grid"><label class="market-field"><span>Khu vực</span><input id="marketCustomerArea" value="${esc(f.route || '')}"></label><label class="market-field"><span>Loại điểm bán</span><input id="marketShopType" placeholder="Cafe / trà sữa / đại lý"></label></div><div class="market-grid"><label class="market-field"><span>Nhu cầu</span><select id="marketDemand"><option value="high">Cao</option><option value="medium">Vừa</option><option value="low">Thấp</option><option value="unknown">Chưa rõ</option></select></label><label class="market-field"><span>Đối thủ chính</span><input id="marketCompetitor"></label></div><label class="market-field"><span>Giá / hàng đối thủ / ghi chú</span><textarea id="marketNoteRow"></textarea></label><label class="market-field"><span>Cơ hội / rủi ro</span><input id="marketOpportunity"></label><label class="market-field"><span>Việc tiếp theo</span><input id="marketNextAction"></label><button class="primary" type="submit">Lưu khách khảo sát</button></form>`; }
function rowList(rows) { if (!rows.length) return '<article class="empty-sync-card">Chưa có khách khảo sát trong file này.</article>'; return rows.map(r => `<article class="market-row" data-open-market-row="${esc(r.id)}"><div><h3>${esc(r.customer_name)}</h3><small>${esc(r.area || '')}${r.customer_phone ? ` · ${esc(r.customer_phone)}` : ''}</small><div class="market-pills"><span>${esc(r.demand || '-')}</span><span>${esc(r.competitor || 'không đối thủ')}</span></div></div><b>Chi tiết ›</b></article>`).join(''); }
function detailHtml(f) { const rows = rowsOf(f.id).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))); return `<div class="market-detail-top"><button id="backToReportList" type="button">‹ Báo cáo</button><b>File báo cáo</b></div><article class="market-summary"><h2>${esc(f.title)}</h2><small>${esc(f.report_date)} · ${esc(f.sales || '-')} · ${rows.length} khách</small><div class="market-pills"><span>${esc(f.route || '-')}</span></div></article>${customerForm(f)}<h3>Khách đã khảo sát</h3>${rowList(rows)}`; }
function renderReports() { if (!listEl) ensureList(); if (!listEl) return; const f = activeFormId ? read(FORM_KEY).find(x => x.id === activeFormId) : null; listEl.innerHTML = f ? detailHtml(f) : filesHtml(); }
function saveCustomer(e) { e.preventDefault(); const f = read(FORM_KEY).find(x => x.id === e.target.dataset.formId); if (!f) return toast('Không thấy file báo cáo.'); const name = $('#marketCustomerName').value.trim(); if (!name) return toast('Thiếu tên khách.'); const rows = read(ROW_KEY); rows.unshift({ id: uid('market-row'), form_id: f.id, customer_name: name, customer_phone: $('#marketCustomerPhone').value.trim(), area: $('#marketCustomerArea').value.trim(), shop_type: $('#marketShopType').value.trim(), demand: $('#marketDemand').value, competitor: $('#marketCompetitor').value.trim(), note: $('#marketNoteRow').value.trim(), opportunity: $('#marketOpportunity').value.trim(), next_action: $('#marketNextAction').value.trim(), created_at: new Date().toISOString(), sync_status: 'local' }); write(ROW_KEY, rows); renderReports(); toast('Đã lưu khách khảo sát.'); }
function bind() { document.querySelector('[data-create-type="market"]')?.addEventListener('click', e => { e.preventDefault(); openForm(); }); $('#closeMarketFormBtn')?.addEventListener('click', closeForm); modal?.addEventListener('click', e => { if (e.target === modal) closeForm(); }); $('#resetMarketBtn')?.addEventListener('click', resetForm); formEl?.addEventListener('submit', saveFile); listEl?.addEventListener('click', e => { const open = e.target.closest('[data-open-report]'); if (open) { activeFormId = open.dataset.openReport; activateReports(); renderReports(); return; } if (e.target.closest('#backToReportList')) { activeFormId = ''; activateReports(); renderReports(); } }); listEl?.addEventListener('submit', e => { if (e.target?.id === 'marketCustomerForm') saveCustomer(e); }); document.querySelector('[data-data-view="reports"]')?.addEventListener('click', () => setTimeout(renderReports, 0)); }
function init() { injectCss(); ensureModal(); ensureList(); resetForm(); bind(); renderReports(); }
if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init, { once: true }); else init();
